# -*- coding: utf-8 -*-
"""vinyl_classification_resnet50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqkAc6OAgQDFJHJ4EoYRQwzQ7Kt6ux9J
"""

# 1. 라이브러리 설치
!pip install segmentation-models-pytorch albumentations --quiet

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import segmentation_models_pytorch as smp
import albumentations as A
from albumentations.pytorch import ToTensorV2

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

# 2. Dataset 클래스 정의
class VinylDataset(Dataset):
    def __init__(self, image_dir, mask_dir, transform=None):
        self.image_paths = sorted(
            [os.path.join(image_dir, f) for f in os.listdir(image_dir)],
            key=lambda x: os.path.splitext(os.path.basename(x))[0].replace('_mask', '')
        )
        self.mask_paths = sorted(
            [os.path.join(mask_dir, f) for f in os.listdir(mask_dir)],
            key=lambda x: os.path.splitext(os.path.basename(x))[0].replace('_mask', '')
        )
        self.transform = transform

        assert len(self.image_paths) == len(self.mask_paths), "이미지와 마스크 개수가 다릅니다."

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img = cv2.imread(self.image_paths[idx])
        mask = cv2.imread(self.mask_paths[idx], cv2.IMREAD_GRAYSCALE)

        if img is None or mask is None:
            raise ValueError(f"파일 읽기 실패: {self.image_paths[idx]}, {self.mask_paths[idx]}")

        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        if self.transform:
            augmented = self.transform(image=img, mask=mask)
            img = augmented['image']
            mask = augmented['mask']

        return img, mask.unsqueeze(0).float() / 255.0

# 3. 경로 설정 및 데이터 준비
IMAGE_DIR = '/content/drive/MyDrive/data/vinyldata'
BINARY_MASK_DIR = '/content/drive/MyDrive/data/vinylmasks_binary'  # 학습용
ORIGINAL_MASK_DIR = '/content/drive/MyDrive/data/vinylmasks'       # 비교용

train_transform = A.Compose([
    A.Resize(512, 512),
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.2),
    A.Normalize(),
    ToTensorV2()
])

# shuffle = False (중요!)
train_dataset = VinylDataset(IMAGE_DIR, BINARY_MASK_DIR, transform=train_transform)
compare_dataset = VinylDataset(IMAGE_DIR, ORIGINAL_MASK_DIR, transform=train_transform)

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=False)
compare_loader = DataLoader(compare_dataset, batch_size=4, shuffle=False)

# 4. 모델 정의
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

model = smp.DeepLabV3Plus(
    encoder_name="resnet50",
    encoder_weights="imagenet",
    in_channels=3,
    classes=1,
).to(DEVICE)

criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

# 5. 학습 루프
EPOCHS = 12
for epoch in range(EPOCHS):
    model.train()
    total_loss = 0

    for imgs, masks in train_loader:
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)

        preds = model(imgs)
        loss = criterion(preds, masks)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"[Epoch {epoch+1}] Loss: {total_loss / len(train_loader):.4f}")

# 6. 시각화 (binary로 학습한 결과 + original 마스크와 비교)
model.eval()
with torch.no_grad():
    for (img_bin, mask_bin), (_, mask_orig) in zip(train_loader, compare_loader):
        img_bin, mask_bin = img_bin.to(DEVICE), mask_bin.to(DEVICE)
        pred = torch.sigmoid(model(img_bin))
        pred = (pred > 0.5).float()

        img_np = img_bin[0].permute(1, 2, 0).cpu().numpy()
        img_np = np.clip(img_np * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406]), 0, 1)

        plt.figure(figsize=(20, 5))
        plt.subplot(1, 4, 1); plt.imshow(img_np); plt.title('Input')
        plt.subplot(1, 4, 2); plt.imshow(mask_orig[0][0].cpu(), cmap='gray'); plt.title('Original Mask')
        plt.subplot(1, 4, 3); plt.imshow(mask_bin[0][0].cpu(), cmap='gray'); plt.title('Binary GT')
        plt.subplot(1, 4, 4); plt.imshow(pred[0][0].cpu(), cmap='gray'); plt.title('Prediction')
        plt.show()
        break

def f1_score(pred, target, threshold=0.5, eps=1e-6):
    pred = (pred > threshold).float()
    target = (target > 0.5).float()

    TP = (pred * target).sum()
    FP = (pred * (1 - target)).sum()
    FN = ((1 - pred) * target).sum()

    precision = (TP + eps) / (TP + FP + eps)
    recall = (TP + eps) / (TP + FN + eps)
    f1 = 2 * (precision * recall) / (precision + recall + eps)
    return f1.item()

model.eval()
f1_scores = []

with torch.no_grad():
    for imgs, masks in train_loader:  # binary 마스크 기준
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
        preds = torch.sigmoid(model(imgs))

        for i in range(imgs.shape[0]):
            f1 = f1_score(preds[i], masks[i])
            f1_scores.append(f1)

print(f"평균 F1-score (Train Set): {np.mean(f1_scores):.4f}")

torch.save(model.state_dict(), "/content/drive/MyDrive/resnet50_vinyl.pth")